export const GET_ERRORS = "GET_ERRORS";

//devices
export const ADD_DEVICE = "ADD_DEVICE";
export const GET_DEVICES = "GET_DEVICES";
export const GET_DEVICE = "GET_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const DELETE_DEVICE = "DELETE_DEVICE";

//fluids
export const ADD_FLUID = "ADD_FLUID";
export const GET_FLUIDS = "GET_FLUIDS";
export const GET_FLUID = "GET_FLUID";
export const UPDATE_FLUID = "UPDATE_FLUID";
export const DELETE_FLUID = "DELETE_FLUID";

//persons
export const ADD_PERSON = "ADD_PERSON";
export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSON = "GET_PERSON";
export const DELETE_PERSON = "DELETE_PERSON";
export const UPDATE_PERSON = "UPDATE_PERSON";

//activity group
export const ADD_GROUP = "ADD_GROUP";
export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUP = "GET_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";

//activity
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_ACTIVITIES_BY_CONNECTION = "GET_ACTIVITIES_BY_CONNECTION";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";

//inspection
export const GET_INSPECTIONS = "GET_INSPECTIONS";
export const GET_INSPECTION = "GET_INSPECTION";
export const GET_INSPECTIONS_BY_CONNECTION = "GET_INSPECTIONS_BY_CONNECTIONS";
export const GET_INSPECTION_BY_CONNECTION = "GET_INSPECTION_BY_CONNECTION";
export const GET_OVERDUE_BY_CONNECTION = "GET_OVERDUE_BY_CONNECTION";
export const CLEAR_INSPECTIONS_LIST_STATE = "CLEAR_INSPECTIONS_LIST_STATE";
export const GET_CONNECTION_START_TIME_BETWEEN = "GET_CONNECTION_START_TIME_BETWEEN";
export const GET_INSPECTION_BY_CONNECTION_STARTTIME_ENDTIME = "GET_INSPECTION_BY_CONNECTION_STARTTIME_ENDTIME";
export const GET_INSPECTIONS_BY_NAME_ACTIONS =
	"GET_INSPECTIONS_BY_NAME_ACTIONS";
export const DELETE_INSPECTION = "DELETE_INSPECTION";

//connection
export const GET_CONNECTIONS = "GET_CONNECTIONS";
export const GET_CONNECTION = "GET_CONNECTION";
export const ADD_CONNECTION = "ADD_CONNECTION";
export const UPDATE_CONNECTION = "UPDATE_CONNECTION";
export const GET_HOMEPAGE_CONNECTIONS = "GET_HOMEPAGE_CONNECTIONS";
export const DELETE_CONNECTION = "DELETE_CONNECTION";

//fluid registry
export const GET_FLUID_REGISTRIES = "GET_FLUID_REGISTRIES";
export const GET_FLUID_REGISTRY = "GET_FLUID_REGISTRY";
export const ADD_FLUID_REGISTRY = "ADD_FLUID_REGISTRY";
export const UPDATE_FLUID_REGISTRY = "UPDATE_FLUID_REGISTRY";
export const DELETE_FLUID_REGISTRY = "DELETE_FLUID_REGISTRY";

//fluid place
export const GET_FLUID_PLACES = "GET_FLUID_PLACES";
export const GET_FLUID_PLACE = "GET_FLUID_PLACE";
export const ADD_FLUID_PLACE = "ADD_FLUID_PLACE";
export const UPDATE_FLUID_PLACE = "UPDATE_FLUID_PLACE";
export const DELETE_FLUID_PLACE = "DELETE_FLUID_PLACE";

//snackbar
export const SET_SNACKBAR = "SET_SNACKBAR";
