export const GET_ERRORS = "GET_ERRORS";

//devices
export const GET_DEVICES = "GET_DEVICES";
export const GET_DEVICE = "GET_DEVICE";
export const DELETE_DEVICE = "DELETE_DEVICE";

//fluids
export const GET_FLUIDS = "GET_FLUIDS";
export const GET_FLUID = "GET_FLUID";
export const DELETE_FLUID = "DELETE_FLUID";

//overview types
export const GET_OVERVIEW_TYPES = "GET_OVERVIEW_TYPES";
export const GET_OVERVIEW_TYPE = "GET_OVERVIEW_TYPE";
export const DELETE_OVERVIEW_TYPE = "DELETE_OVERVIEW_TYPE";

//persons
export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSON = "GET_PERSON";
export const DELETE_PERSON = "DELETE_PERSON";

//activity group
export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUP = "GET_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

//activity
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

//overview
export const GET_OVERVIEWS = "GET_OVERVIEWS";
export const GET_OVERVIEW = "GET_OVERVIEW";
export const GET_OVERVIEWS_BY_CONNECTION = "GET_OVERVIEWS_BY_CONNECTION";
export const CLEAR_OVERVIEWS_LIST_STATE = "CLEAR_OVERVIEWS_LIST_STATE";
export const GET_OVERVIEWS_BY_NAME_ACTIONS = "GET_OVERVIEWS_BY_NAME_ACTIONS";
export const DELETE_OVERVIEW = "DELETE_OVERVIEW";

//connection
export const GET_CONNECTIONS = "GET_CONNECTIONS";
export const GET_CONNECTION = "GET_CONNECTION";
export const GET_PERIODIC_CONNECTION = "GET_PERIODIC_CONNECTION";
export const GET_ON_DEMAND_CONNECTION = "GET_ON_DEMAND_CONNECTION";
export const DELETE_CONNECTION = "DELETE_CONNECTION";

//role
export const GET_ROLES = "GET_ROLES";
export const GET_ROLE = "GET_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";

//fluid registry
export const GET_FLUID_REGISTRIES = "GET_FLUID_REGISTRIES";
export const GET_FLUID_REGISTRY = "GET_FLUID_REGISTRY";
export const DELETE_FLUID_REGISTRY = "DELETE_FLUID_REGISTRY";

//fluid place
export const GET_FLUID_PLACES = "GET_FLUID_PLACES";
export const GET_FLUID_PLACE = "GET_FLUID_PLACE";
export const DELETE_FLUID_PLACE = "DELETE_FLUID_PLACE";
